// <auto-generated />
using System.Collections.Generic;
using HappyTravel.EdoLocationUpdater.Common.Models;
using HappyTravel.EdoLocationUpdater.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HappyTravel.EdoLocationUpdater.Data.Migrations
{
    [DbContext(typeof(LocationUpdaterContext))]
    [Migration("20201112142101_RenameProviderSupplier")]
    partial class RenameProviderSupplier
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:PostgresExtension:postgis", ",,")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("HappyTravel.Data.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<Point>("Coordinates")
                        .HasColumnType("geography (point)");

                    b.Property<string>("Country")
                        .HasColumnType("jsonb");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<string>("Locality")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .HasColumnType("jsonb");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<List<Suppliers>>("Suppliers")
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
